Added recommendation system
sdgniser/arc pull request #18
Opened 2022-02-12 17:53 UTC by rahul3613

Added a section for recommendations on the home page. Which will recommend files to the users based on their similarity with other users in accessing files.

2022-02-12 17:53 UTC, pep8speaks commented
Hello @rahul3613! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`main/recom.py`](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py):

> [Line 8:41](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L8): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 19:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L19): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 21:19](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L21): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 31:40](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L31): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 32:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L32): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 35:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L35): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 39:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L39): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 61:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L61): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 65:26](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L65): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 68:26](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L68): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 73:26](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L73): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 77:26](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L77): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 85:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L85): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 89:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/recom.py#L89): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace



* In the file [`main/views.py`](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py):

> [Line 31:39](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L31): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 31:41](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L31): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 33:27](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L33): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 33:29](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L33): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 33:36](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L33): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 33:38](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L33): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 33:45](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L33): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 33:47](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L33): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 38:37](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L38): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 43:80](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L43): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 79 characters)
> [Line 43:81](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L43): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 43:97](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L43): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 43:117](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L43): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 268:39](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L268): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 268:41](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L268): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 269:16](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L269): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 271:32](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L271): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 271:34](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L271): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 278:1](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L278): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 280:39](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L280): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 280:41](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L280): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 281:16](https://github.com/sdgniser/arc/blob/1c4c054e78a4dc1f99d0472b75ad65f4d7c449c0/main/views.py#L281): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2022-02-17 02:36 UTC, paniash commented
Hi! Could you correct the PEP styling as the bot mentioned?

2022-02-18 07:26 UTC, JeS24 requested changes
Short review of the code. Additionally, you need to do the following:
1. Change function names e.g. update1 and file_view1. Make them slightly more descriptive. Or, try to merge them with the original functions, update and file_view.
2. Put comments and docstrings in all files and functions and methods that you have added.
3. Explain how the recommendation system works. You could do it through dosctrings in the code or you can write a [Gist](https://gist.github.com/), that we can later add as a Wiki page for this repo. It will be helpful for repo maintainers and future contributors.
4. After all the code (+ comments) is finalized, run [`black`](https://pypi.org/project/black/) on the code to properly format it.

Finally, we will need to squash the commits before merging.

2022-02-18 07:26 UTC, JeS24 commented on main/templates/main/recom.htm
> +          {% if auth == 1 %}
`{% if auth %}` works.

2022-02-18 07:26 UTC, JeS24 commented on main/templates/main/recom.htm
> +                    <div class="gallery" style="color:rgb(255, 0, 0);line-height: 0.8em;">
Styles in .css as much as possible.

2022-02-18 07:26 UTC, JeS24 commented on main/recom.py
> +def get(user_id):
Rename this function to something more informational, like get_recs() or get_recommendations() etc.

2022-02-18 07:26 UTC, JeS24 commented on main/views.py
> +start()
Use a separate python script (file) to start this and keep this running.

2022-02-18 07:26 UTC, JeS24 commented on requirements.txt
> +lockfile>=0.12.2
`lockfile` is deprecated and not under development since 2015. Perhaps you can use [fasteners](https://pypi.org/project/fasteners/).

2022-02-18 07:26 UTC, JeS24 commented on main/recom.py
> +        else:
If the possibilities that come out from the `if` statement are mutually exclusive, then you don't need the `else` statement. For example,
```
if 2 > 0:
    return 2
else:
    return 0
```
can be written as:
```
if 2 > 0:
    return 2

return 0
```
In your code, you could write:
```
if user_id in df.columns:
    if len(df)>0:
        corr = df.corr()[user_id]
        ...
        return final.index.tolist()   

    return []


while lock.is_locked():
    sleep(0.05)

...

return []
```

This applies to a lot of other places in your code. But do check the logic to ensure that mutual exclusivity is present.

2022-02-19 22:00 UTC, rahul3613 commented
Hi, @JeS24 I have made all the changes suggested by you. Please have a look,
Here is the [link for the Gist](https://gist.github.com/rahul3613/f0c4e4bbf5377c2c933f9d077f8b001f) explaining how the recommendation system works. (I don't know where to put it)
Regarding 'squashing the commits' I think it can be easily done while merging from your side?

2022-02-24 13:29 UTC, 11DE784A commented
Hi. Thanks for making the changes. Here are a few suggestions:

1. Make the recommendations section on the homepage less intrusive, just add a single line which has a list of recommendations. Instead of
![Screenshot 2022-02-24 at 18-09-08 Home NISER Archive](https://user-images.githubusercontent.com/31156132/155532536-3587ed51-f12b-4e94-853f-7a1e3860ccc9.png)
have something like
![Screenshot 2022-02-24 at 18-52-42 Home NISER Archive](https://user-images.githubusercontent.com/31156132/155532598-e5b45255-ca94-4639-96a5-0054e45ee7d0.png)

2. Instead of calling `read_csv` everytime with `update` and `get_recom` declare a global dataframe and save the variable to file occasionally.

2022-02-24 13:33 UTC, 11DE784A commented on main/recom.py
> +            df.loc[[file], [user_id]] = 10
This statement occurs in each of the four conditions. You should move this to outside the entire if block.

2022-02-24 13:34 UTC, 11DE784A commented on main/templates/main/recom.htm
> +      <p hidden style="text-align: right;margin-top: -20px;">rec/self: {{ count.rec }}/{{ count.own }}</p>
As before, move style information to CSS

2022-02-24 13:39 UTC, 11DE784A commented on main/views.py
> +# Normal file view (used when file is accessed through normal browsing)
Writing two functions with almost identical contents is really bad.

2022-02-24 13:43 UTC, 11DE784A commented on recom_data.csv
> +Files,1
No need to track this file. Add to gitignore.

2022-03-11 14:38 UTC, 11DE784A commented
Everything looks fine to me. Will merge soon.

2022-03-12 03:47 UTC, JeS24 commented
@rahul3613 The description in the gist is nicely presented. We are almost ready to merge. One last change, I would need from your side is if you can use either the numpydoc or the Google documentation system, since those are standard and can make parsing very simple for existing docs-related packages. And, run `black` on the files you have modified, so that, we conform to PEP8 norms.

@11DE784A We can merge, if no runtime issues have come up in your local testing. Please do squash the commits.

2022-03-12 20:33 UTC, rahul3613 commented
Hi, @JeS24 & @11DE784A I have changed the docstring format to "numpydoc". Please have a look.

2022-05-29 09:03 UTC, 11DE784A commented
Looks good to me.
Please merge and close @Abhishek-Deshmukh

2022-06-22 15:04 UTC, JeS24 commented
Looks good. We can merge.

2022-06-22 15:04 UTC, merged

2022-06-22 15:04 UTC, JeS24 commented
Thanks @rahul3613.